### ISSUE TITLE
Overly complex

### ISSUE THREAD

**Issue by j4m-can** [NucciTheBoss/charming-exercises#13]
https://github.com/NucciTheBoss/charming-exercises/blob/20e2c30e57d8fb3d41dac342b6542f2f6d3b7b55/hot-potato/src/charm.py#L24-L66

I understand what you were wanting to do from our discussion. At this point, the ```Forward.forward()``` seems overly complex to simply pick up the token from the **last** unit and have the matching one act on it.

**Comment by NucciTheBoss** [comment]
Hmm. It does not feel too complex to me, but that is probably because I am the one who wrote the method. Which part seems too complex? I mostly just used recursion so that I would not lose time sending the data from the target unit to another unit, and then back again to the target unit so that I could trigger the `RelationChanged` event handler in the target unit.

**Comment by NucciTheBoss** [comment]
I feel think that is what I am doing here? I use recursion to rerun the function if the unit is handing the token off to itself. If the token is being handed off to a new unit, it returns the token which is then used to update the bucket.

**Comment by j4m-can** [comment]
Then it is not overly complex!

**Comment by NucciTheBoss** [comment]
Sweet! Thank you!
